name: modular_flutter
description: A Flutter package for managing modular architecture, inspired by Laravel Modules (nwidart/laravel-modules)
version: 0.1.0
homepage: https://github.com/lisoingsem/modular-flutter.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.2
  path: ^1.9.0
  meta: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

executables:
  modular_flutter: modular_flutter

flutter:
  uses-material-design: true

